name: Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo into runner
        uses: actions/checkout@v4

      - name: Install uv - Python package manager
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Check migrations
        run: |
          uv run python manage.py makemigrations --check --dry-run
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      
      - name: Check deployment readiness
        run: |
          uv run python manage.py check --deploy
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: False
          DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1